### ISSUE TITLE
Import "pru" could not be resolvedPylancereportMissingImports)

### ISSUE THREAD

**Issue by akademsubotnik** [yasirroni/pru#22]
Hi,

After I run 'pip install pru'.  I try to import pru in my python code, with 

"from pru import (
    get_installed_requirements_packages_and_version,
    get_installed_packages_name_and_version,
    replace_requirements_packages_versions,
    upgrade_requirements,
)"  

but I get an error that 

"Import "pru" could not be resolvedPylance[reportMissingImports]"

when I run 'pip list' from the CLI I see pru as an installed package

- subotnik

**Comment by yasirroni** [comment]
Hi @akademsubotnik, thanks for using `pru`. Can you share with me how you install `pru`? I run this code in jupyter and it works.

```jupyter
!pip install pru

from pru import (
    get_installed_requirements_packages_and_version,
    get_installed_packages_name_and_version,
    replace_requirements_packages_versions,
    upgrade_requirements,
)
```
___

Also, `pru` support CLI command if you seems can't import it on your machine.

**Comment by akademsubotnik** [comment]
Thanks @yasirroni , I am able to get pru working on the CLI.  
I am using VSCode.

I am also trying to use pru in a python program.  I install pru from the CLI with 'pip install pru'.  Next I add:
into my python program, but it gives the error that pru is not found.
![prunotfound](https://github.com/user-attachments/assets/529783bc-3419-4ed4-b417-107e013c74f3)"

**Comment by yasirroni** [comment]
@akademsubotnik Have you tried to run the code? It might be just `Pylance` linter error.

**Comment by akademsubotnik** [comment]
let me check

**Comment by akademsubotnik** [comment]
I am able to import pru in a python file on another computer, sorry for creating the issue!!  Thanks for helping me 😄 
![image](https://github.com/user-attachments/assets/d042a62f-860a-489d-a8cb-df2a2076cb9f)
